name: Build with Maven (PR)

on:
  pull_request:
    branches: [ master ]

env:
  MAVEN_CLI_OPTS: --fail-at-end --errors -Dstyle.color=always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn $MAVEN_CLI_OPTS clean verify

      - name: Generate Code Coverage Report
        run: mvn $MAVEN_CLI_OPTS jacoco:report jacoco:report-integration

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Analyze by Sonar
        run: mvn $MAVEN_CLI_OPTS org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bullet-tooth_logback-kafka-appender
        env:
          # Needed to get some information about the pull request, if any
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
